In [2]:
import pandas as pd
df = pd.read_excel("../데이터파일/data_preprocess.xlsx")
df

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
2       Mia    NaN    Sejong       Cashiers
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
7   Abigail   24.0     Busan        Waiters
8     Emily   31.0       NaN         Driver
9     Henry   43.0     Daegu         Doctor

In [3]:
df_modi = df.drop_duplicates()
df_modi

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
2       Mia    NaN    Sejong       Cashiers
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
8     Emily   31.0       NaN         Driver
9     Henry   43.0     Daegu         Doctor

In [5]:
df_modi.dropna(inplace=True)
df_modi

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
9     Henry   43.0     Daegu         Doctor

In [6]:
df_modi.loc[6, "age"] = 18
df_modi

       name   age   address            job
0   Jackson  27.0   Gangwon          Sales
1     Lucas  15.0     Seoul   Student(mid)
3   Abigail  24.0     Busan        Waiters
4     James  28.0      Jeju        Analyst
5  Benjamin  34.0  Gyeonggi       Cashiers
6   William  18.0     Ulsan  Student(high)
9     Henry  43.0     Daegu         Doctor

In [7]:
df["name"]
df[["age", "job"]]

     age            job
0   27.0          Sales
1   15.0   Student(mid)
2    NaN       Cashiers
3   24.0        Waiters
4   28.0        Analyst
5   34.0       Cashiers
6  180.0  Student(high)
7   24.0        Waiters
8   31.0         Driver
9   43.0         Doctor

In [8]:
df_coll = df_modi["name"]
print(type(df_coll))

df_coll2 = df_modi[["name", "job"]]
print(df_coll2)

<class 'pandas.Series'>
       name            job
0   Jackson          Sales
1     Lucas   Student(mid)
3   Abigail        Waiters
4     James        Analyst
5  Benjamin       Cashiers
6   William  Student(high)
9     Henry         Doctor

In [9]:
print(df_modi.loc[3])
print(df_modi.iloc[3])

name       Abigail
age           24.0
address      Busan
job        Waiters
Name: 3, dtype: object
name         James
age           28.0
address       Jeju
job        Analyst
Name: 4, dtype: object

In [10]:
df_modi["age"] = df_modi["age"].astype(int)
print(df_modi.head())

       name  age   address           job
0   Jackson   27   Gangwon         Sales
1     Lucas   15     Seoul  Student(mid)
3   Abigail   24     Busan       Waiters
4     James   28      Jeju       Analyst
5  Benjamin   34  Gyeonggi      Cashiers

In [11]:
df_modi.sort_values(by=["name"], ascending=False)
df_modi

       name  age   address            job
0   Jackson   27   Gangwon          Sales
1     Lucas   15     Seoul   Student(mid)
3   Abigail   24     Busan        Waiters
4     James   28      Jeju        Analyst
5  Benjamin   34  Gyeonggi       Cashiers
6   William   18     Ulsan  Student(high)
9     Henry   43     Daegu         Doctor